# Run with: 
# docker login quay.io
# docker compose -f quay.docker-compose.yml up 
version: '3.9'


services:
  quay:
      image: quay.io/projectquay/quay:latest
      command: config my-secret-password
      ports:
        - "8443:8443"
      privileged: true


  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: quayuser
      POSTGRES_PASSWORD: quaypassword
      POSTGRES_DB: quaydb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
  quay-config:
  quay-storage:
